namespace :docker do
  def make_tag(ruby_version, python_version, mxnet_version)
    name = 'mrkn/mxnet-rb-ci'
    return [name, [ruby_version, python_version, mxnet_version].join('-')].join(':')
  end

  def make_build_args(ruby_version, python_version, mxnet_version)
    ba = '--build-arg'
    return [
      ba, "RUBY_VERSION=#{ruby_version}",
      ba, "PYTHON_VERSION=#{python_version}",
      ba, "MXNET_VERSION=#{mxnet_version}"
    ]
  end

  def generate_dockerfile(ruby_version, &block)
    require 'erb'
    require 'tempfile'
    dir = File.dirname(__FILE__)
    Tempfile.open('Dockerfile') do |tempfile|
      src = File.join(dir, 'Dockerfile.erb')
      File.write(tempfile, ERB.new(File.read(src)).result(binding))
      yield tempfile
    end
  end

  def docker_build(ruby_version, python_version, mxnet_version)
    tag = make_tag(ruby_version, python_version, mxnet_version)
    build_args = make_build_args(ruby_version, python_version, mxnet_version)
    generate_dockerfile(ruby_version) do |dockerfile|
      sh 'docker', 'build', '-f', dockerfile.path, '-t', tag, *build_args, '.'
    end
  end

  def docker_push(ruby_version, python_version, mxnet_version)
    tag = make_tag(ruby_version, python_version, mxnet_version)
    build_args = make_build_args(ruby_version, python_version, mxnet_version)
    sh 'docker', 'push', tag
  end

  def run_all(task)
    %w[
      2.6.6
      2.6.0
      2.5.3
      2.4.5
      2.3.8
    ].each do |ruby_version|
      ENV['ruby_version'] = ruby_version
      Rake::Task[task].invoke
      Rake::Task[task].reenable
    end
  end

  task :build do
    ruby_version = ENV['ruby_version'] || '2.6.6'
    python_version = ENV['python_version'] || '3.7.2'
    mxnet_version = ENV['mxnet_version'] || '1.7.0'
    docker_build(ruby_version, python_version, mxnet_version) 
  end

  namespace :build do
    task :all do
      run_all('docker:build')
    end
  end

  task :push do
    ruby_version = ENV['ruby_version'] || '2.6.6'
    python_version = ENV['python_version'] || '3.7.2'
    mxnet_version = ENV['mxnet_version'] || '1.7.0'
    docker_push(ruby_version, python_version, mxnet_version) 
  end

  namespace :push do
    task :all do
      run_all('docker:push')
    end
  end
end
