namespace :ci do
  def get_image_name
    ruby_version = ENV['ruby_version'] || '2.6.6'
    python_version = ENV['python_version'] || '3.7.0'
    mxnet_version = ENV['mxnet_version'] || '1.7.0'
    return ['mrkn/mxnet-rb-ci', [ruby_version, python_version, mxnet_version].join('-')].join(':')
  end

  task :pull do
    sh 'docker', 'pull', get_image_name
  end

  task :run do
    sh 'docker', 'run', '--rm', '-t', '-v', "#{Dir.pwd}:/work", get_image_name, '/bin/sh', '-c', 'ci/script'
  end
end
